{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kauailabs.navx.frc",
    "module": "navx-java",
    "version": "4.0.412",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "olagkpuoyfcgjk76hiptmrtjti"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        }
      ],
      "files": [
        {
          "name": "navx-java-4.0.412.jar",
          "url": "navx-java-4.0.412.jar",
          "size": 71288,
          "sha512": "fbe93a03fde819a9b230f5149f2053f81a26c88b0db076efd7743cc08ce0d7b68230ec5c7a9cd78b7cd4573f2956246a243309d379be29d0ff660f1131beba57",
          "sha256": "4c73d09e16f362c401522a224c11ea9d1124a5fd798bca32da3e0a9400d73e3e",
          "sha1": "559bbe4098a520da66977be7381e94e79cc2d4a5",
          "md5": "fc5018fbbb7df75c872be3cf34d8f4b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2021.+"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        }
      ],
      "files": [
        {
          "name": "navx-java-4.0.412.jar",
          "url": "navx-java-4.0.412.jar",
          "size": 71288,
          "sha512": "fbe93a03fde819a9b230f5149f2053f81a26c88b0db076efd7743cc08ce0d7b68230ec5c7a9cd78b7cd4573f2956246a243309d379be29d0ff660f1131beba57",
          "sha256": "4c73d09e16f362c401522a224c11ea9d1124a5fd798bca32da3e0a9400d73e3e",
          "sha1": "559bbe4098a520da66977be7381e94e79cc2d4a5",
          "md5": "fc5018fbbb7df75c872be3cf34d8f4b0"
        }
      ]
    }
  ]
}
